In [50]:
import pandas as pd
import numpy as np

In [51]:
crop_df = pd.read_csv("../data/raw/crop_yield.csv")
weather_df = pd.read_csv("../data/external/state_weather_data_1997_2020.csv")
soil_df = pd.read_csv("../data/external/state_soil_data.csv")

In [52]:
crop_df.head()

,Crop,Crop_Year,Season,State,Area,Production,Annual_Rainfall,Fertilizer,Pesticide,Yield
0,Arecanut,1997,Whole Year,Assam,73814.0,56708,2051.4,7024878.38,22882.34,0.796087
1,Arhar/Tur,1997,Kharif,Assam,6637.0,4685,2051.4,631643.29,2057.47,0.710435
2,Castor seed,1997,Kharif,Assam,796.0,22,2051.4,75755.32,246.76,0.238333
3,Coconut,1997,Whole Year,Assam,19656.0,126905000,2051.4,1870661.52,6093.36,5238.051739
4,Cotton(lint),1997,Kharif,Assam,1739.0,794,2051.4,165500.63,539.09,0.420909

In [53]:
weather_df.head()

            state  year  avg_temp_c  total_rainfall_mm  avg_humidity_percent
0  Andhra Pradesh  1997       28.21            1191.08                 69.56
1  Andhra Pradesh  1998       28.21            1100.41                 71.95
2  Andhra Pradesh  1999       28.03             603.67                 66.91
3  Andhra Pradesh  2000       27.74            1070.25                 70.73
4  Andhra Pradesh  2001       28.08             910.13                 68.69

In [54]:
soil_df.head()

               state   N   P   K   pH
0     Andhra Pradesh  78  45  22  6.8
1  Arunachal Pradesh  55  15  35  5.5
2              Assam  60  18  38  5.8
3              Bihar  85  30  25  7.2
4       Chhattisgarh  70  35  20  6.5

In [55]:
crop_df.shape

(19689, 10)

In [56]:
soil_df.shape

(30, 5)

In [57]:
weather_df.shape

(720, 5)

In [58]:
crop_df.columns

Index(['Crop', 'Crop_Year', 'Season', 'State', 'Area', 'Production',
       'Annual_Rainfall', 'Fertilizer', 'Pesticide', 'Yield'],
      dtype='object')

In [59]:
weather_df.columns

Index(['state', 'year', 'avg_temp_c', 'total_rainfall_mm',
       'avg_humidity_percent'],
      dtype='object')

In [60]:
soil_df.columns

Index(['state', 'N', 'P', 'K', 'pH'], dtype='object')

In [61]:
crop_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 19689 entries, 0 to 19688
Data columns (total 10 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Crop             19689 non-null  object
 1   Crop_Year        19689 non-null  int64
 2   Season           19689 non-null  object
 3   State            19689 non-null  object
 4   Area             19689 non-null  float64
 5   Production       19689 non-null  int64
 6   Annual_Rainfall  19689 non-null  float64
 7   Fertilizer       19689 non-null  float64
 8   Pesticide        19689 non-null  float64
 9   Yield            19689 non-null  float64
dtypes: float64(5), int64(2), object(3)
memory usage: 1.5+ MB

In [62]:
weather_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 720 entries, 0 to 719
Data columns (total 5 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   state                 720 non-null    object
 1   year                  720 non-null    int64
 2   avg_temp_c            720 non-null    float64
 3   total_rainfall_mm     720 non-null    float64
 4   avg_humidity_percent  720 non-null    float64
dtypes: float64(3), int64(1), object(1)
memory usage: 28.3+ KB

In [63]:
soil_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30 entries, 0 to 29
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   state   30 non-null     object
 1   N       30 non-null     int64
 2   P       30 non-null     int64
 3   K       30 non-null     int64
 4   pH      30 non-null     float64
dtypes: float64(1), int64(3), object(1)
memory usage: 1.3+ KB

In [64]:
crop_df.describe()

,Crop_Year,Area,Production,Annual_Rainfall,Fertilizer,Pesticide,Yield
count,19689.000000,1.968900e+04,1.968900e+04,19689.000000,1.968900e+04,1.968900e+04,19689.000000
mean,2009.127584,1.799266e+05,1.643594e+07,1437.755177,2.410331e+07,4.884835e+04,79.954009
std,6.498099,7.328287e+05,2.630568e+08,816.909589,9.494600e+07,2.132874e+05,878.306193
min,1997.000000,5.000000e-01,0.000000e+00,301.300000,5.417000e+01,9.000000e-02,0.000000
25%,2004.000000,1.390000e+03,1.393000e+03,940.700000,1.880146e+05,3.567000e+02,0.600000
50%,2010.000000,9.317000e+03,1.380400e+04,1247.600000,1.234957e+06,2.421900e+03,1.030000
75%,2015.000000,7.511200e+04,1.227180e+05,1643.700000,1.000385e+07,2.004170e+04,2.388889
max,2020.000000,5.080810e+07,6.326000e+09,6552.700000,4.835407e+09,1.575051e+07,21105.000000

In [65]:
weather_df.describe()

              year  avg_temp_c  total_rainfall_mm  avg_humidity_percent
count   720.000000  720.000000         720.000000            720.000000
mean   2008.500000   23.383389        1388.461083             64.825764
std       6.926999    4.968676         672.503842             12.148615
min    1997.000000    6.260000         249.240000             34.470000
25%    2002.750000   22.265000         914.985000             54.615000
50%    2008.500000   25.115000        1231.830000             68.710000
75%    2014.250000   26.580000        1702.595000             74.567500
max    2020.000000   28.630000        5363.280000             86.060000

In [66]:
soil_df.describe()

                N          P          K         pH
count   30.000000  30.000000  30.000000  30.000000
mean    75.566667  31.466667  33.333333   6.553333
std     22.730328  12.386682   7.594614   0.763717
min     50.000000  15.000000  20.000000   5.500000
25%     60.500000  20.000000  28.500000   5.900000
50%     70.000000  29.000000  34.500000   6.450000
75%     80.000000  41.500000  38.000000   7.075000
max    150.000000  55.000000  50.000000   8.000000

In [67]:
crop_df.isnull().sum()

Crop               0
Crop_Year          0
Season             0
State              0
Area               0
Production         0
Annual_Rainfall    0
Fertilizer         0
Pesticide          0
Yield              0
dtype: int64

In [68]:
weather_df.isnull().sum()

state                   0
year                    0
avg_temp_c              0
total_rainfall_mm       0
avg_humidity_percent    0
dtype: int64

In [69]:
soil_df.isnull().sum()

state    0
N        0
P        0
K        0
pH       0
dtype: int64

In [70]:
crop_df.duplicated().sum()

np.int64(0)

In [71]:
weather_df.duplicated().sum()

np.int64(0)

In [72]:
soil_df.duplicated().sum()

np.int64(0)

In [73]:
crop_df.nunique()

Crop                  55
Crop_Year             24
Season                 6
State                 30
Area               13644
Production         14016
Annual_Rainfall      634
Fertilizer         18598
Pesticide          17405
Yield              13551
dtype: int64

In [74]:
weather_df.nunique()

state                    30
year                     24
avg_temp_c              488
total_rainfall_mm       694
avg_humidity_percent    633
dtype: int64

In [75]:
soil_df.nunique()

state    30
N        23
P        20
K        18
pH       24
dtype: int64

In [76]:
crop_df["Yield"]

0           0.796087
1           0.710435
2           0.238333
3        5238.051739
4           0.420909
            ...
19684       0.500000
19685       3.000000
19686       1.285000
19687       0.016667
19688       1.261818
Name: Yield, Length: 19689, dtype: float64

In [80]:
## Initial Observations

## Crop dataset contains ____ rows and ____ columns.
## Weather dataset contains ____ rows and ____ columns.
## Soil dataset contains ____ rows and ____ columns.
## Target variable is ______.
## Missing values found in ______ columns.
## Duplicate rows found: ______.
## Data types include numerical and categorical features.