In [1]:
import pandas as pd

In [2]:
crop_df = pd.read_csv("../data/processed/crop_yield_cleaned.csv")
weather_df = pd.read_csv("../data/processed/weather_cleaned.csv")
soil_df = pd.read_csv("../data/processed/soil_cleaned.csv")

In [3]:
crop_df.columns

Index(['Crop', 'Year', 'Season', 'State', 'Area', 'Production',
       'Annual_Rainfall', 'Fertilizer', 'Pesticide', 'Yield'],
      dtype='object')

In [4]:
weather_df.columns

Index(['state', 'year', 'avg_temp_c', 'total_rainfall_mm',
       'avg_humidity_percent'],
      dtype='object')

In [13]:
weather_df.rename(columns={"year":"Year"},
                  inplace = True)
weather_df.rename(columns ={"state":"State"},
                  inplace = True)

In [14]:
weather_df.columns

Index(['State', 'Year', 'avg_temp_c', 'total_rainfall_mm',
       'avg_humidity_percent'],
      dtype='object')

In [5]:
soil_df.columns

Index(['state', 'N', 'P', 'K', 'pH'], dtype='object')

In [17]:
soil_df.rename(columns ={"state":"State"}, 
               inplace = True )

In [18]:
soil_df.columns

Index(['State', 'N', 'P', 'K', 'pH'], dtype='object')

# Merge Crop + Weather

In [15]:
crop_weather = pd.merge(crop_df,weather_df,
                        on =["State","Year"],
                        how = "left")

# Merge with Soil

In [19]:
final_df = pd.merge(crop_weather,soil_df,
                    on = ["State"],
                    how = "left")

In [20]:
final_df.head()

,Crop,Year,Season,State,Area,Production,Annual_Rainfall,Fertilizer,Pesticide,Yield,avg_temp_c,total_rainfall_mm,avg_humidity_percent,N,P,K,pH
0,Arecanut,1997,Whole Year,Assam,73814.0,56708,2051.4,7024878.38,22882.34,0.796087,22.41,1468.92,70.71,60.0,18.0,38.0,5.8
1,Arhar/Tur,1997,Kharif,Assam,6637.0,4685,2051.4,631643.29,2057.47,0.710435,22.41,1468.92,70.71,60.0,18.0,38.0,5.8
2,Castor Seed,1997,Kharif,Assam,796.0,22,2051.4,75755.32,246.76,0.238333,22.41,1468.92,70.71,60.0,18.0,38.0,5.8
3,Coconut,1997,Whole Year,Assam,19656.0,126905000,2051.4,1870661.52,6093.36,5238.051739,22.41,1468.92,70.71,60.0,18.0,38.0,5.8
4,Cotton(Lint),1997,Kharif,Assam,1739.0,794,2051.4,165500.63,539.09,0.420909,22.41,1468.92,70.71,60.0,18.0,38.0,5.8

In [21]:
final_df.shape

(19689, 17)

In [22]:
final_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 19689 entries, 0 to 19688
Data columns (total 17 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Crop                  19689 non-null  object
 1   Year                  19689 non-null  int64
 2   Season                19689 non-null  object
 3   State                 19689 non-null  object
 4   Area                  19689 non-null  float64
 5   Production            19689 non-null  int64
 6   Annual_Rainfall       19689 non-null  float64
 7   Fertilizer            19689 non-null  float64
 8   Pesticide             19689 non-null  float64
 9   Yield                 19689 non-null  float64
 10  avg_temp_c            19058 non-null  float64
 11  total_rainfall_mm     19058 non-null  float64
 12  avg_humidity_percent  19058 non-null  float64
 13  N                     19058 non-null  float64
 14  P                     19058 non-null  float64
 15  K                     19058 non-null  float64
 16  pH                    19058 non-null  float64
dtypes: float64(12), int64(2), object(3)
memory usage: 2.6+ MB

In [23]:
final_df.isnull().sum()

Crop                      0
Year                      0
Season                    0
State                     0
Area                      0
Production                0
Annual_Rainfall           0
Fertilizer                0
Pesticide                 0
Yield                     0
avg_temp_c              631
total_rainfall_mm       631
avg_humidity_percent    631
N                       631
P                       631
K                       631
pH                      631
dtype: int64

In [25]:
final_df[final_df["avg_temp_c"].isnull()]

,Crop,Year,Season,State,Area,Production,Annual_Rainfall,Fertilizer,Pesticide,Yield,avg_temp_c,total_rainfall_mm,avg_humidity_percent,N,P,K,pH
10939,Arhar/Tur,2008,Rabi,Jammu And Kashmir,22.0,12,1390.1,3146.88,1.98,0.550000,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10940,Barley,2008,Rabi,Jammu And Kashmir,9747.0,4724,1390.1,1394210.88,877.23,0.585000,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10941,Garlic,2008,Rabi,Jammu And Kashmir,604.0,516,1390.1,86396.16,54.36,0.825556,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10942,Gram,2008,Rabi,Jammu And Kashmir,284.0,155,1390.1,40623.36,25.56,0.545000,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10943,Linseed,2008,Rabi,Jammu And Kashmir,126.0,97,1390.1,18023.04,11.34,0.782000,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18784,Turmeric,2013,Rabi,Jammu And Kashmir,4.0,4,1193.8,577.96,1.08,0.930000,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18785,Wheat,2013,Rabi,Jammu And Kashmir,292380.0,464577,1193.8,42245986.20,78942.60,1.270000,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19686,Maize,1997,Kharif,Jammu And Kashmir,310883.0,440900,1356.2,29586735.11,96373.73,1.285000,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19687,Rice,1997,Kharif,Jammu And Kashmir,275746.0,5488,1356.2,26242746.82,85481.26,0.016667,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19688,Wheat,1997,Rabi,Jammu And Kashmir,239344.0,392160,1356.2,22778368.48,74196.64,1.261818,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [26]:
sorted(crop_df["State"].unique())

['Andhra Pradesh',
 'Arunachal Pradesh',
 'Assam',
 'Bihar',
 'Chhattisgarh',
 'Delhi',
 'Goa',
 'Gujarat',
 'Haryana',
 'Himachal Pradesh',
 'Jammu And Kashmir',
 'Jharkhand',
 'Karnataka',
 'Kerala',
 'Madhya Pradesh',
 'Maharashtra',
 'Manipur',
 'Meghalaya',
 'Mizoram',
 'Nagaland',
 'Odisha',
 'Puducherry',
 'Punjab',
 'Sikkim',
 'Tamil Nadu',
 'Telangana',
 'Tripura',
 'Uttar Pradesh',
 'Uttarakhand',
 'West Bengal']

In [27]:
sorted(weather_df["State"].unique())

['Andhra Pradesh',
 'Arunachal Pradesh',
 'Assam',
 'Bihar',
 'Chhattisgarh',
 'Delhi',
 'Goa',
 'Gujarat',
 'Haryana',
 'Himachal Pradesh',
 'Jammu and Kashmir',
 'Jharkhand',
 'Karnataka',
 'Kerala',
 'Madhya Pradesh',
 'Maharashtra',
 'Manipur',
 'Meghalaya',
 'Mizoram',
 'Nagaland',
 'Odisha',
 'Puducherry',
 'Punjab',
 'Sikkim',
 'Tamil Nadu',
 'Telangana',
 'Tripura',
 'Uttar Pradesh',
 'Uttarakhand',
 'West Bengal']

In [28]:
sorted(soil_df["State"].unique())

['Andhra Pradesh',
 'Arunachal Pradesh',
 'Assam',
 'Bihar',
 'Chhattisgarh',
 'Delhi',
 'Goa',
 'Gujarat',
 'Haryana',
 'Himachal Pradesh',
 'Jammu and Kashmir',
 'Jharkhand',
 'Karnataka',
 'Kerala',
 'Madhya Pradesh',
 'Maharashtra',
 'Manipur',
 'Meghalaya',
 'Mizoram',
 'Nagaland',
 'Odisha',
 'Puducherry',
 'Punjab',
 'Sikkim',
 'Tamil Nadu',
 'Telangana',
 'Tripura',
 'Uttar Pradesh',
 'Uttarakhand',
 'West Bengal']

In [29]:
crop_states = set(crop_df["State"].unique())
weather_states = set(weather_df["State"].unique())

print("States in Crop but not in Weather:")
print(sorted(crop_states - weather_states))

print("\nStates in Weather but not in Crop:")
print(sorted(weather_states - crop_states))

States in Crop but not in Weather:
['Jammu And Kashmir']

States in Weather but not in Crop:
['Jammu and Kashmir']

In [30]:
soil_states = set(soil_df["State"].unique())

print("States in Crop but not in Soil:")
print(sorted(crop_states - soil_states))

print("\nStates in Soil but not in Crop:")
print(sorted(soil_states - crop_states))

States in Crop but not in Soil:
['Jammu And Kashmir']

States in Soil but not in Crop:
['Jammu and Kashmir']

In [39]:
state_mapping = {
    "Jammu And Kashmir" : "Jammu and Kashmir"
}

In [40]:
crop_df["State"] = crop_df["State"].replace(state_mapping)

In [41]:
crop_df["State"]

0                    Assam
1                    Assam
2                    Assam
3                    Assam
4                    Assam
               ...
19684             Nagaland
19685             Nagaland
19686    Jammu and Kashmir
19687    Jammu and Kashmir
19688    Jammu and Kashmir
Name: State, Length: 19689, dtype: object

In [33]:
sorted(crop_df["State"].unique())
sorted(weather_df["State"].unique())

['Andhra Pradesh',
 'Arunachal Pradesh',
 'Assam',
 'Bihar',
 'Chhattisgarh',
 'Delhi',
 'Goa',
 'Gujarat',
 'Haryana',
 'Himachal Pradesh',
 'Jammu and Kashmir',
 'Jharkhand',
 'Karnataka',
 'Kerala',
 'Madhya Pradesh',
 'Maharashtra',
 'Manipur',
 'Meghalaya',
 'Mizoram',
 'Nagaland',
 'Odisha',
 'Puducherry',
 'Punjab',
 'Sikkim',
 'Tamil Nadu',
 'Telangana',
 'Tripura',
 'Uttar Pradesh',
 'Uttarakhand',
 'West Bengal']

In [42]:
crop_weather = pd.merge(
    crop_df,
    weather_df,
    on = ["State","Year"],
    how = "left"
)

In [43]:
final_df = pd.merge(
    crop_weather,
    soil_df,
    on = ["State"],
    how = "left"
)

In [44]:
final_df.isnull().sum()

Crop                    0
Year                    0
Season                  0
State                   0
Area                    0
Production              0
Annual_Rainfall         0
Fertilizer              0
Pesticide               0
Yield                   0
avg_temp_c              0
total_rainfall_mm       0
avg_humidity_percent    0
N                       0
P                       0
K                       0
pH                      0
dtype: int64

In [45]:
final_df

,Crop,Year,Season,State,Area,Production,Annual_Rainfall,Fertilizer,Pesticide,Yield,avg_temp_c,total_rainfall_mm,avg_humidity_percent,N,P,K,pH
0,Arecanut,1997,Whole Year,Assam,73814.0,56708,2051.4,7024878.38,22882.34,0.796087,22.41,1468.92,70.71,60,18,38,5.8
1,Arhar/Tur,1997,Kharif,Assam,6637.0,4685,2051.4,631643.29,2057.47,0.710435,22.41,1468.92,70.71,60,18,38,5.8
2,Castor Seed,1997,Kharif,Assam,796.0,22,2051.4,75755.32,246.76,0.238333,22.41,1468.92,70.71,60,18,38,5.8
3,Coconut,1997,Whole Year,Assam,19656.0,126905000,2051.4,1870661.52,6093.36,5238.051739,22.41,1468.92,70.71,60,18,38,5.8
4,Cotton(Lint),1997,Kharif,Assam,1739.0,794,2051.4,165500.63,539.09,0.420909,22.41,1468.92,70.71,60,18,38,5.8
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19684,Small Millets,1998,Kharif,Nagaland,4000.0,2000,1498.0,395200.00,1160.00,0.500000,18.55,915.19,69.91,56,16,36,5.8
19685,Wheat,1998,Rabi,Nagaland,1000.0,3000,1498.0,98800.00,290.00,3.000000,18.55,915.19,69.91,56,16,36,5.8
19686,Maize,1997,Kharif,Jammu and Kashmir,310883.0,440900,1356.2,29586735.11,96373.73,1.285000,8.63,447.57,52.51,70,25,42,6.7
19687,Rice,1997,Kharif,Jammu and Kashmir,275746.0,5488,1356.2,26242746.82,85481.26,0.016667,8.63,447.57,52.51,70,25,42,6.7
19688,Wheat,1997,Rabi,Jammu and Kashmir,239344.0,392160,1356.2,22778368.48,74196.64,1.261818,8.63,447.57,52.51,70,25,42,6.7

In [48]:
final_df.to_csv("../data/processed/final_df.csv",index = False)

# Markdown Observations

## Document:

## Number of rows and columns
## Merge keys used
## Any unmatched records
## Additional cleaning required